apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-partner-production
  namespace: production
spec:
  replicas: 2
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-partner
        env: production
    spec:
     volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-partner:v5
        name: piggyback-prod-runner-partner
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/secret.json
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-partner
          containerPort: 8085
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8085
status: {}
